import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Ahaget",
  description: "Ahaget Terms of Service. Read the full legal agreement governing your use of the Ahaget platform.",
};

const sections = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    content: `By accessing or using the Ahaget platform ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not access or use the Service.

These Terms constitute a legally binding agreement between you (or the company you represent, "Customer") and Ahaget Inc. ("Ahaget", "we", "us", or "our"). If you are accepting these Terms on behalf of a company or other legal entity, you represent that you have the authority to bind that entity.`,
  },
  {
    id: "description",
    title: "2. Description of Service",
    content: `Ahaget provides an AI-powered onboarding platform that allows software companies to embed guided agent experiences into their web applications. The Service includes:

- A JavaScript widget that embeds into Customer applications
- A dashboard for building, configuring, and monitoring onboarding flows
- AI processing infrastructure for understanding and responding to end-user questions and actions
- Analytics and failure reporting tools
- MCP connector infrastructure for integrating with Customer APIs`,
  },
  {
    id: "accounts",
    title: "3. Accounts and Registration",
    content: `You must provide accurate and complete information when creating an account. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.

You must promptly notify us of any unauthorized use of your account or any other breach of security. Ahaget will not be liable for any loss or damage resulting from unauthorized use of your account.

You may not use another person's account without permission. Accounts are non-transferable.`,
  },
  {
    id: "free-tier",
    title: "4. Free Tier",
    content: `Ahaget offers a free tier that includes up to 3 AI agents and 100 Monthly Tracked Users (MTU). The free tier is available indefinitely, subject to the following conditions:

- Free tier usage may not be used for commercial purposes that would otherwise require a paid plan
- We reserve the right to modify free tier limits with 30 days prior written notice
- We may suspend free tier accounts that are inactive for more than 180 consecutive days, with prior notice`,
  },
  {
    id: "billing",
    title: "5. Billing and Payment",
    content: `Paid plans are billed monthly or annually in advance. All prices are in US Dollars unless otherwise stated.

Upgrades to a higher tier take effect immediately and are charged on a prorated basis for the current billing cycle. Downgrades take effect at the start of the next billing cycle.

You must provide a valid payment method. By providing a payment method, you authorize Ahaget to charge the applicable fees. If payment fails, we will notify you and may suspend your account after a grace period of 7 days.

All fees are non-refundable except where required by law or as explicitly stated in these Terms.`,
  },
  {
    id: "data",
    title: "6. Data and Privacy",
    content: `Customer Data: You retain all ownership rights to your content and data. Ahaget processes Customer Data solely to provide the Service and as described in our Privacy Policy.

End User Data: Session transcripts and conversation data generated by your end users belong to you. Ahaget does not use this data to train AI models.

Retention: Customer Data is retained for the duration of your subscription plus 90 days following termination. Free tier data is retained for 180 days of inactivity.

Data Processing: For customers subject to GDPR, a Data Processing Agreement (DPA) is available on request at privacy@useahaget.ai.`,
  },
  {
    id: "usage",
    title: "7. Acceptable Use",
    content: `You may not use the Service to:

- Violate any applicable law or regulation
- Deceive or mislead your end users about the nature of any AI interaction
- Transmit malicious code or interfere with the Service's infrastructure
- Scrape or extract data from the Service beyond normal usage
- Circumvent any usage limits or restrictions
- Resell or sublicense the Service without written permission from Ahaget

We reserve the right to suspend accounts that violate these restrictions, with or without prior notice depending on severity.`,
  },
  {
    id: "ip",
    title: "8. Intellectual Property",
    content: `Ahaget IP: The Service, including all software, algorithms, interfaces, and documentation, is owned by Ahaget and protected by intellectual property laws. These Terms do not grant you any ownership rights in the Service.

Customer IP: You retain all rights to your customer data, flow configurations, and any content you upload to the Service.

Feedback: If you provide suggestions or feedback about the Service, you grant Ahaget a royalty-free license to use that feedback without restriction.`,
  },
  {
    id: "sla",
    title: "9. Service Availability",
    content: `Ahaget targets 99.9% uptime for the widget delivery infrastructure and 99.5% for the dashboard. Planned maintenance is announced at least 24 hours in advance.

Current and historical uptime is published at status.useahaget.ai. Service credits for downtime may be requested by contacting support and are available to paid plan customers only.`,
  },
  {
    id: "liability",
    title: "10. Limitation of Liability",
    content: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, Ahaget SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, OR GOODWILL.

Ahaget'S TOTAL LIABILITY TO YOU FOR ANY CLAIMS ARISING UNDER THESE TERMS SHALL NOT EXCEED THE GREATER OF (A) $100 OR (B) THE AMOUNT YOU PAID TO Ahaget IN THE 12 MONTHS PRECEDING THE CLAIM.

Some jurisdictions do not allow the exclusion of certain warranties or limitation of liability, so some of the above limitations may not apply to you.`,
  },
  {
    id: "termination",
    title: "11. Termination",
    content: `Either party may terminate these Terms at any time. You may terminate by cancelling your account in the dashboard. Ahaget may terminate for material breach with 14 days notice, or immediately for violations of the Acceptable Use policy.

Upon termination, your right to use the Service ceases immediately. We will make Customer Data available for export for 30 days post-termination, after which it will be deleted.`,
  },
  {
    id: "changes",
    title: "12. Changes to Terms",
    content: `We may update these Terms from time to time. For material changes, we will provide at least 30 days notice via email or dashboard notification. Continued use of the Service following the effective date constitutes your acceptance of the new Terms.

If you do not agree to any updated Terms, you may terminate your account before the effective date.`,
  },
  {
    id: "governing",
    title: "13. Governing Law",
    content: `These Terms are governed by the laws of the State of Delaware, United States, without regard to its conflict of law provisions. Any disputes shall be resolved in the state or federal courts located in Delaware.

For customers in the European Union, certain mandatory provisions of local law may apply.`,
  },
  {
    id: "contact",
    title: "14. Contact",
    content: `For questions about these Terms:

Email: hello@useahaget.ai
Address: Ahaget Inc., [address on file]

For privacy and data requests: privacy@useahaget.ai
For security issues: security@useahaget.ai`,
  },
];

export default function TermsPage() {
  return (
    <div className="pt-16 bg-white">
      {/* Header */}
      <div className="border-b border-slate-100 bg-[#fafbfc]">
        <div className="max-w-4xl mx-auto px-6 py-16">
          <p className="eyebrow mb-3">Legal</p>
          <h1 className="text-4xl md:text-5xl font-black text-slate-900 mb-4">Terms of Service</h1>
          <div className="flex flex-wrap gap-x-8 gap-y-2 text-sm text-slate-500">
            <span>Last updated: April 1, 2026</span>
            <span>Effective: April 1, 2026</span>
          </div>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-6 py-16">
        <div className="grid grid-cols-1 lg:grid-cols-[220px_1fr] gap-12">

          {/* Sidebar nav */}
          <aside className="hidden lg:block">
            <div className="sticky top-24">
              <p className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-4">Contents</p>
              <nav className="space-y-1">
                {sections.map((s) => (
                  <a
                    key={s.id}
                    href={`#${s.id}`}
                    className="block text-sm text-slate-500 hover:text-brand py-1 transition-colors leading-snug"
                  >
                    {s.title}
                  </a>
                ))}
              </nav>
              <div className="mt-8 pt-6 border-t border-slate-100 space-y-2">
                <Link href="/security" className="block text-sm text-brand hover:text-brand-dark font-medium transition-colors">
                  Security →
                </Link>
                <a href="mailto:hello@useahaget.ai" className="block text-sm text-slate-500 hover:text-slate-900 transition-colors">
                  Contact us
                </a>
              </div>
            </div>
          </aside>

          {/* Body */}
          <article className="prose prose-slate max-w-none">
            <p className="text-lg text-slate-500 leading-relaxed mb-12 not-prose border-l-4 border-brand/30 pl-4">
              These are the full Terms of Service governing your use of the Ahaget platform. Please read them carefully. By using Ahaget, you agree to be bound by these terms.
            </p>

            {sections.map((section) => (
              <div key={section.id} id={section.id} className="mb-12 scroll-mt-24">
                <h2 className="text-xl font-black text-slate-900 mb-4 not-prose">{section.title}</h2>
                <div className="space-y-3">
                  {section.content.split("\n\n").map((para, i) => {
                    if (para.startsWith("- ")) {
                      const items = para.split("\n").filter((l) => l.startsWith("- "));
                      return (
                        <ul key={i} className="space-y-1.5 not-prose">
                          {items.map((item, j) => (
                            <li key={j} className="flex items-start gap-2 text-slate-600 text-sm leading-relaxed">
                              <span className="w-1.5 h-1.5 rounded-full bg-brand mt-1.5 flex-shrink-0" />
                              {item.slice(2)}
                            </li>
                          ))}
                        </ul>
                      );
                    }
                    return (
                      <p key={i} className="text-slate-600 text-sm leading-relaxed not-prose whitespace-pre-line">
                        {para}
                      </p>
                    );
                  })}
                </div>
              </div>
            ))}

            <div className="mt-16 pt-10 border-t border-slate-100 not-prose">
              <p className="text-sm text-slate-400 text-center">
                © {new Date().getFullYear()} Ahaget Inc. — All rights reserved.
              </p>
            </div>
          </article>
        </div>
      </div>
    </div>
  );
}
